server:
  port: 8777
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/action?useSSL=false&useUnicode=true&autoReconnect=true&allowMultiQueries=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
xxl:
  job:
    admin:
      addresses: http://192.168.200.39:9090/xxl-job-admin
    executor:
      appname: analysisJudge
      ip:
      port: 8654
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    ### xxl-job, access token
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: cestc-xxl-job


